In [8]:
#importar librerias
import pandas as pd
import numpy as np


In [50]:
#cargamos los datos
df = pd.read_csv("StudentsPerformance.csv")

In [12]:
#Realizamos una vista a las primera filas de los datos.
df.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [14]:
np.mean(df['math score'])

66.089

In [15]:
np.mean(df)

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [ ]:
#Nota: La media a veces no es un valor muy representativo porque es suceptible a valores atipicos.

## Ejemplo: 



En una compañía que cuenta con tres empleados, se tiene la siguiente estructura de salarios mensuales:

- Dos programadores ganan cada uno $3,000.
- Un jefe (Chief) gana $20,000.

Todos los salarios están expresados en dólares. Determinar el promedio de los salarios y la mediana. Explicar como el salario se ve afectado por el valor atipico del salario del chef.



In [17]:
salarios = [3000,3000,20000]

In [19]:
promedio_salarios = np.mean(salarios)
print(promedio_salarios)

8666.666666666666


In [20]:
# En este caso, el promedio no es muy representativo de los salarios.

In [22]:
# Mediana???

np.median(salarios)

3000.0

In [23]:
#Analicemos el data frame de los estudiantes
df.describe()

math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [24]:
#Calculemos la mediana y la media de la variable math score
np.mean(df['math score'])

66.089

In [25]:
np.median(df['math score'])

66.0

In [26]:
#Calculemos la mediana y la media de la variable reading score
print(np.mean(df['reading score']))
print(np.median(df['reading score']))


69.169
70.0


In [27]:
#Ejemplos:

lista1= [4,5,5,6,3,4,6]
lista2= [9,2,3,5,10,8]

In [30]:
print(np.mean(lista1))
print(np.mean(lista2))

4.714285714285714
6.166666666666667


In [32]:
print(np.std(lista1))
print(np.std(lista2))

1.0301575072754257
3.0230595245361758


### Ejemplo :

En un juego de baloncesto entre un grupo de 10 amigos, la escena se complica cuando Juan, un aficionado a la estadística, plantea su descontento respecto a la conformación de los equipos. Con un ojo agudo para los números, argumenta que el promedio de estatura en uno de los equipos supera al del otro. Enfrentados a este dilema, el reto consiste en calcular de manera meticulosa el promedio de estatura tanto del grupo completo como de cada uno de los equipos por separado. A partir de los datos proporcionados, calcular el promedio de estatura de todos los integrantes y de cada uno de los equipos con el fin de confirmar o refutar la hipótesis de Juan.

Equipo 1: 170, 165, 178, 160, 175

Equipo 2: 175, 179, 168, 178, 163


In [35]:
import numpy as np


equipo1 = [170, 165, 178, 160, 175]
equipo2 = [175, 179, 168, 178, 163]

np.mean()

### Ejemplo 2:

Usted ha sido designado para desarrollar una aplicación móvil que rastree el tiempo dedicado al ejercicio por parte de un usuario. Los datos registrados de un usuario, que reflejan la cantidad de minutos que ha empleado la aplicación cada día durante un período de 10 días, se presentan a continuación:

91, 76, 80, 113, 110, 80, 76, 85, 89, 93

Calcular la mediana de los datos.


In [36]:
times =[91, 76, 80, 113, 110, 80, 76, 85, 89, 93]
np.median(times)

87.0

In [37]:
np.mean(times)

89.3

In [38]:
np.std(times)

12.458330546265016

In [42]:
np.sort(times)


array([ 76,  76,  80,  80,  85,  89,  91,  93, 110, 113])

In [43]:
np.mean(times)

89.3

In [47]:
# Cuartiles:# Calcula los cuartiles de math score

np.quantile(df['math score'],[0,0.3,1])

array([  0.,  59., 100.])

In [49]:
# Cuartiles:# Calcula los cuartiles de reading score

np.quantile(df['reading score'],[0,0.25,0.5,0.75,1])

array([ 17.,  59.,  70.,  79., 100.])